### ISSUE TITLE
support --standalone on OS X

### ISSUE THREAD

**Issue by ctismer** [pyside/pyside-setup#31]
For the sake of simplicity on OS X, it would be good to support --standalone.

The question is if this should become also the default for the distribution
and get rid of any mention of homebrew for installing Qt ?

**Comment by ctismer** [comment]
I think I should implement that, ASAP, since that avoids ambigous situations with Qt5 and homebrew not linking the lib.

**Comment by lck** [comment]
Fixed with version 1.2.4

**Comment by lck** [comment]
This was closed by mistake
