### ISSUE TITLE
error: Error configuring shiboken

### ISSUE THREAD

**Issue by sprintyu** [pyside/pyside-setup#36]
Install pyside via pip, error occurred.

Could you help to solve this problem?

Thanks!
## Installing log:

(py2)~/Downloads/PySide-1.2.2$ pip install pyside
Downloading/unpacking pyside
  Using download cache from /Users/shiwei/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FP%2FPySide%2FPySide-1.2.2.tar.gz
  Running setup.py (path:/Users/shiwei/Dropbox/workspace/py2/build/pyside/setup.py) egg_info for package pyside
    Removing /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_package

```
package init file 'pyside_package/PySide/__init__.py' not found (or not a regular file)
package init file 'pyside_package/pysideuic/__init__.py' not found (or not a regular file)
warning: no previously-included files matching '**' found under directory 'sources/pyside-examples/examples/hyperui'
warning: no previously-included files matching '**' found under directory 'sources/pyside-examples/mobility'
warning: no previously-included files matching '**' found under directory 'sources/shiboken/.git'
warning: no previously-included files matching '**' found under directory 'sources/pyside/.git'
warning: no previously-included files matching '**' found under directory 'sources/pyside-tools/.git'
warning: no previously-included files matching '**' found under directory 'sources/pyside-examples/.git'
warning: no files found matching '**' under directory 'pyside_package/PySide'
warning: no files found matching '**' under directory 'pyside_package/PySide/docs'
warning: no files found matching '**' under directory 'pyside_package/PySide/plugins'
warning: no files found matching '**' under directory 'pyside_package/PySide/imports'
warning: no files found matching '**' under directory 'pyside_package/PySide/translations'
warning: no files found matching '**' under directory 'pyside_package/PySide/include'
warning: no files found matching '**' under directory 'pyside_package/PySide/typesystems'
warning: no files found matching '**' under directory 'pyside_package/PySide/examples'
warning: no files found matching '**' under directory 'pyside_package/pysideuic'
warning: no files found matching '**' under directory 'pyside_package/pysideuic/Compiler'
warning: no files found matching '**' under directory 'pyside_package/pysideuic/port_v2'
warning: no files found matching '**' under directory 'pyside_package/pysideuic/port_v3'
warning: no files found matching '**' under directory 'pyside_package/pysideuic/widget-plugins'
```

Installing collected packages: pyside
  Running setup.py install for pyside
    Removing /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_package
    Python architecture is 64bit
    Inserting path "/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release/bin" to environment
    ==============================
    Package version: 1.2.2
    Build type: Release
    Build tests: False
    ---
    Make path: /usr/bin/make
    Make generator: Unix Makefiles
    Make jobs:
    ---
    Script directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside
    Sources directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/sources
    Build directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release
    Install directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release
    Python site-packages install directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release/lib/python2.7/site-packages
    ---
    Python executable: /Users/shiwei/Dropbox/workspace/py2/bin/python2.7
    Python includes: /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/include/python2.7
    Python library: /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
    Python prefix: /Users/shiwei/Dropbox/workspace/py2
    Python scripts: /Users/shiwei/Dropbox/workspace/py2/bin
    ---
    Qt qmake: /usr/local/bin/qmake
    Qt version: 4.8.6
    Qt bins: /usr/local/Cellar/qt/4.8.6/bin
    Qt plugins: /usr/local/Cellar/qt/4.8.6/plugins
    ---
    OpenSSL libs: None
    ==============================
    Creating build folder /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release...
    Creating install folder /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release...
    Building module shiboken...
    Creating module build folder /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken...
    Configuring module shiboken (/Users/shiwei/Dropbox/workspace/py2/build/pyside/sources/shiboken)...
    Running process: /usr/local/bin/cmake -G "Unix Makefiles" -DQT_QMAKE_EXECUTABLE=/usr/local/bin/qmake -DBUILD_TESTS=False -DDISABLE_DOCSTRINGS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release /Users/shiwei/Dropbox/workspace/py2/build/pyside/sources/shiboken -DPYTHON_EXECUTABLE=/Users/shiwei/Dropbox/workspace/py2/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DALTERNATIVE_QT_INCLUDE_DIR=/usr/local/Cellar/qt/4.8.6/include
    /usr/local/bin/cmake -G Unix Makefiles -DQT_QMAKE_EXECUTABLE=/usr/local/bin/qmake -DBUILD_TESTS=False -DDISABLE_DOCSTRINGS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release /Users/shiwei/Dropbox/workspace/py2/build/pyside/sources/shiboken -DPYTHON_EXECUTABLE=/Users/shiwei/Dropbox/workspace/py2/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DALTERNATIVE_QT_INCLUDE_DIR=/usr/local/Cellar/qt/4.8.6/include
    -- The C compiler identification is AppleClang 6.0.0.6000054
    -- The CXX compiler identification is AppleClang 6.0.0.6000054
    CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/Platform/Darwin.cmake:211 (message):
      CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:

```
   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".
error: Error configuring shiboken
Complete output from command /Users/shiwei/Dropbox/workspace/py2/bin/python2.7 -c "import setuptools, tokenize;__file__='/Users/shiwei/Dropbox/workspace/py2/build/pyside/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/zr/9m3wfl1s21s6f_jjymdzs2j00000gn/T/pip-2BK3Up-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shiwei/Dropbox/workspace/py2/bin/../include/site/python2.7:
Removing /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_package
```

running install

running build

Python architecture is 64bit

Inserting path "/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release/bin" to environment
# 

Package version: 1.2.2

Build type: Release

Build tests: False

---

Make path: /usr/bin/make

Make generator: Unix Makefiles

Make jobs:

---

Script directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside

Sources directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/sources

Build directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release

Install directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release

Python site-packages install directory: /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release/lib/python2.7/site-packages

---

Python executable: /Users/shiwei/Dropbox/workspace/py2/bin/python2.7

Python includes: /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/include/python2.7

Python library: /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib

Python prefix: /Users/shiwei/Dropbox/workspace/py2

Python scripts: /Users/shiwei/Dropbox/workspace/py2/bin

---

Qt qmake: /usr/local/bin/qmake

Qt version: 4.8.6

Qt bins: /usr/local/Cellar/qt/4.8.6/bin

Qt plugins: /usr/local/Cellar/qt/4.8.6/plugins

---

OpenSSL libs: None
# 

Creating build folder /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release...

Creating install folder /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release...

Building module shiboken...

Creating module build folder /Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken...

Configuring module shiboken (/Users/shiwei/Dropbox/workspace/py2/build/pyside/sources/shiboken)...

Running process: /usr/local/bin/cmake -G "Unix Makefiles" -DQT_QMAKE_EXECUTABLE=/usr/local/bin/qmake -DBUILD_TESTS=False -DDISABLE_DOCSTRINGS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release /Users/shiwei/Dropbox/workspace/py2/build/pyside/sources/shiboken -DPYTHON_EXECUTABLE=/Users/shiwei/Dropbox/workspace/py2/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DALTERNATIVE_QT_INCLUDE_DIR=/usr/local/Cellar/qt/4.8.6/include

/usr/local/bin/cmake -G Unix Makefiles -DQT_QMAKE_EXECUTABLE=/usr/local/bin/qmake -DBUILD_TESTS=False -DDISABLE_DOCSTRINGS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_install/py2.7-qt4.8.6-64bit-release /Users/shiwei/Dropbox/workspace/py2/build/pyside/sources/shiboken -DPYTHON_EXECUTABLE=/Users/shiwei/Dropbox/workspace/py2/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DALTERNATIVE_QT_INCLUDE_DIR=/usr/local/Cellar/qt/4.8.6/include

-- The C compiler identification is AppleClang 6.0.0.6000054

-- The CXX compiler identification is AppleClang 6.0.0.6000054

CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/Platform/Darwin.cmake:211 (message):

  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set

  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to

  empty.

Call Stack (most recent call first):

  /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)

  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!

See also "/Users/shiwei/Dropbox/workspace/py2/build/pyside/pyside_build/py2.7-qt4.8.6-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".

error: Error configuring shiboken

---

Cleaning up...
Command /Users/shiwei/Dropbox/workspace/py2/bin/python2.7 -c "import setuptools, tokenize;**file**='/Users/shiwei/Dropbox/workspace/py2/build/pyside/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/zr/9m3wfl1s21s6f_jjymdzs2j00000gn/T/pip-2BK3Up-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shiwei/Dropbox/workspace/py2/bin/../include/site/python2.7 failed with error code 1 in /Users/shiwei/Dropbox/workspace/py2/build/pyside
Storing debug log for failure in /Users/shiwei/.pip/pip.log

**Comment by gogeccc** [comment]
I know that this might be annoying, but today I run into the same issue.

**Comment by jhh3000** [comment]
having the same issue. have qt installed.

**Comment by ZelphirKaltstahl** [comment]
Bump. Having the same issue. Is anyone reading this?

**Comment by RiteshPanda** [comment]
Bump ! I need the solution too .

**Comment by joergsimon** [comment]
would have the same problem currently. any ideas?

**Comment by gogeccc** [comment]
Install pyside package via your distro's package manager.

**Comment by JorgeVenzor** [comment]
I have the same problem and I see that this have been a bug for several years now

**Comment by NICK-DUAN** [comment]
good, everyone have this problem but nobody can solve it?i also got this. bad day

**Comment by fredrikaverpil** [comment]
Not sure why this repo hasn't been archived (made read-only) as the pyside-setup project is abandoned in favor for PySide2: https://github.com/pyside/pyside2-setup


Please note that [this](http://code.qt.io/cgit/pyside/pyside-setup.git/) is where the real work is taking place and that you should be filing issues [here](https://bugreports.qt.io/projects/PYSIDE/issues/), and not in github.
