### ISSUE TITLE
compiling fails

### ISSUE THREAD

**Issue by ix-** [PySide/pyside-setup#41]
.. code: bash
    >>> git clone https://github.com/PySide/pyside-setup.git pyside-setup
    >>> cd /path/to/pyside-setup
    >>> python3 setuo.py build --version=1.3.0de

build.log: http://pastebin.com/EhXfYWem

**Comment by ctismer** [comment]
On 29.03.15 03:34, ix- wrote:
>
> .. code: bash
> >>> git clone https://github.com/PySide/pyside-setup.git pyside-setup
> >>> cd /path/to/pyside-setup
> >>> python3 setuo.py build --version=1.3.0de
>

What crap is this?
I don't believe in anything that is called "setuo.py".
A version "1.3.0de" is also non-existent.
Please avoid such sloppy posts. They will not be answered.

Regards - Chris

-- 
Christian Tismer             :^)   tismer@stackless.com
Software Consulting          :     http://www.stackless.com/
Karl-Liebknecht-Str. 121     :     http://www.pydica.net/
14482 Potsdam                :     GPG key -> 0xFB7BEE0E
phone +49 173 24 18 776  fax +49 (30) 700143-0023

**Comment by ix-** [comment]
neat. did you bother to look inside of the build? If it seems sloppy to you that I misspelled 'setup' how about you make sure that you check out the build log at least? Dude, I'm no programmer, I effing tried to build pyside from source for the package provided by my distro fails... as it turns out, the source does, too. If you don't like feedback, then don't have an issue page!

**Comment by ctismer** [comment]
You gave no info about your platform. You did not give any hint about your environment. You misspelled simple things instead of doing an exact copy. You demanded that I read a pastebin copy, searching for hints what might have gone wrong, after you failed all the obvious minimum things from above? You seem to think I have to serve you, as my "customer"? I disagree.

**Comment by ctismer** [comment]
Without further information about your Linux distribution, we cannot help you.
The install works on OSX, Windows and a couple of Linuxen, with wheels and native builds.
Your problem can be a compiler version issue, a special problem with some distribution, a collision
of certain package version or whatnot. 
Please provide information about Linux distribution, Code name, special installs and every
non-standard feature like different C-compilers.

Looking into the listing suggests some compiler issue, but without further info this is a waste of time to look into.

**Comment by ix-** [comment]
yeah, well I disagree too, but it was never my purpose to be served. I wanted to provide the info that I cannot compile your software (and thereby giving feedback) and I glady provide you with the data you need, I simply did not know what it was, and I wanted to be brief so that you do not have to go through irrelevant info... turns out you took it as an affront.
I run funtoo linux, gcc version is x86_64-pc-linux-gnu-4.8.4, pyside version according to your __init__.py is 1.2.2. Do you need something else?

**Comment by ctismer** [comment]
Hmm - I have to install Funtoo Linux and see if I can find the problem. Do I see this right?
No clue so far... can I install FunToo as a VM? I'm running OS/X Yosemite natively, but with Win7 as a Parallels virtual site.
Cheers -- Chris

**Comment by ix-** [comment]
No, you don't, I have. Tell me what you need and I'll provide it or tell me to stop asking for help.

**Comment by ctismer** [comment]
Can you give me a hint for downloading FunToo? I will then try to set this up as a virtual, and then seek for the compile error. Just give me the needed steps, and I will do that.
It is my intent to have PySide work everywhere. (although you could meanwhile move to PyQt, as I heared.
Thanks -- Chris

**Comment by ix-** [comment]
Do you use docker? there are 2 builds. Else https://funtoo.org . But I guess that is quite a lot of work. 
In build log there is something `QtGui/PySide/QtGui/pyside_qtgui_python.h:1802:42: error ::QGtkStyle’ has not been declared` and I used a 'patch' that excludes QGtkStyle. After that I can compile but lack the Gtk support.
 
Gentoo bug report: https://bugs.gentoo.org/show_bug.cgi?id=530764
Patch: https://530764.bugs.gentoo.org/attachment.cgi?id=390634

**Comment by ctismer** [comment]
Ok, what I'm going to try is:
- download your OS version
- install it at a minimum
- try to build PySide
- try to make a match of the error messages with some known issue

If that does not work, then I'll begin to patch the source and track problems down.
This can take days and weeks of work.

Just asking -- is it worth that effort, or is it just for fun? If it is relevant work, I will do that.
Regards -- Chris

**Comment by ctismer** [comment]
ah, no, I don't use docker so far. Sorry, late tonite...I need to stop for now.

**Comment by ix-** [comment]
No not at all. I need pyside for freecad. I'll manage to find a work around somehow. If I find a solution I'll post it here. Thanks for your effort.

**Comment by ix-** [comment]
Turns out I did not set the gtkstyle flag when compiling qtgui. Hence the message "::QGtkStyle has not been declared" (https://bugs.funtoo.org/browse/FL-2222). Thanks for your time and sorry again for a clumsy attempt to file a bug report.
