### ISSUE TITLE
"pyside_postinstall.py -install" dumps a RunTimeError

### ISSUE THREAD

**Issue by baslack** [PySide/pyside-setup#42]
Attempting to get PySide up and running on a fairly old Mac.
OS: 10.8.5
QT: 4.8.6 (installed via Homebrew)
Python: 2.7.9 (installed via Homebrew)
PIP: 6.1.1
XCode: 5.1.1

Following the procedure on the wiki, I get to the post install script run and I get the following traceback from it. Not quite sure how to proceed from here.

Traceback (most recent call last):
  File "/usr/local/bin/pyside_postinstall.py", line 321, in <module>
    install()
  File "/usr/local/bin/pyside_postinstall.py", line 31, in install
    install_posix()
  File "/usr/local/bin/pyside_postinstall.py", line 231, in install_posix
    rpath_cmd(pyside_path, srcpath)
  File "/usr/local/bin/pyside_postinstall.py", line 215, in rpath_cmd
    localize_libpaths(srcpath, pyside_libs, pyside_path)
  File "/usr/local/bin/pyside_postinstall.py", line 181, in localize_libpaths
    (install_name, install_name, libpath))
  File "/usr/local/bin/pyside_postinstall.py", line 90, in back_tick
    raise RuntimeError(cmd + ' process returned code %d' % retcode)
RuntimeError: install_name_tool -change libpyside-python2.7.1.2.dylib @rpath/libpyside-python2.7.1.2.dylib /usr/local/lib/python2.7/site-packages/PySide/libpyside-python2.7.1.2.2.dylib process returned code 1

**Comment by ctismer** [comment]
Ok, so for some reason, the command in line 90 does not work.
This is exactly the listed command in the error message:
```
RuntimeError: install_name_tool -change libpyside-python2.7.1.2.dylib @rpath/libpyside-python2.7.1.2.dylib /usr/local/lib/python2.7/site-packages/PySide/libpyside-python2.7.1.2.2.dylib process returned code 1
```

You should then try to run this command by hand and find out what went wrong.
- is the command "install_name_tool" found, or is the path in error?
- is there another, previously installed version of the dylib, that might need more priviledges to install? Then uninstall that before.
- maybe run "brew doctor" and see if it complains

Hope this helps -- Chris

**Comment by baslack** [comment]
That did it, ctismer. The site packages directory showed a "can not access, insufficient permissions" error when I ran the command by itself. Fixed it and the post install ran correctly. Thanks for your help.

**Comment by ctismer** [comment]
Yeah, these subprocess calls still suffer from too little error output.
But I'm glad that it worked for you!.
Maybe you had an older install before, or just by chance have installed python with sudo, which probably takes the privileged user.
Anyway, I will try if I can make the error output more verbose.

Cheers - Chris
