### ISSUE TITLE
Compilation on linux : mention libqtwebkit-dev

### ISSUE THREAD

**Issue by NotSqrt** [PySide/pyside-setup#43]
When using ``apt-get install --no-install-recommends`` (to limit the amount of packages to the necessary), it is necessary to add ``libqtwebkit-dev``, otherwise the webkit part of pyside will **silently not compile**.

Thanks !

**Comment by cjermain** [comment]
Thanks @NotSqrt! That solves the missing QtWebKit issue when building from the source.
