### ISSUE TITLE
QtDesigner/QtDesigner file not found building against DMG qt installer

### ISSUE THREAD

**Issue by matthew-brett** [pyside/pyside-setup#45]
I am trying to build against Qt 4.8.6 from the DMG installer : http://download.qt.io/archive/qt/4.8/4.8.6/qt-opensource-mac-4.8.6-1.dmg

Once I have installed `sphinx==1.1.3`, all goes well until:

```
[  2%] Building CXX object plugins/CMakeFiles/uiplugin.dir/customwidgets.cpp.o
...
In file included from /Users/mb312/dev_trees/pyside-wheels/pyside-setup/sources/pyside/plugins/customwidgets.cpp:23:
/Users/mb312/dev_trees/pyside-wheels/pyside-setup/sources/pyside/plugins/customwidget.h:27:10: fatal error: 
      'QtDesigner/QtDesigner' file not found
#include <QtDesigner/QtDesigner>
         ^
2 warnings and 1 error generated.
make[2]: *** [plugins/CMakeFiles/uiplugin.dir/customwidgets.cpp.o] Error 1
make[1]: *** [plugins/CMakeFiles/uiplugin.dir/all] Error 2
make: *** [all] Error 2
```

This is odd, because if I compile a tiny c++ file from the command line:

```
#include <iostream>
#include <QtDesigner/QtDesigner>

using namespace std;

int main()
{
    cout << "Hello World" << endl;
}
```

this works fine.

Do y'all have any idea why C++ is not finding the headers during the build?

**Comment by OAkyildiz** [comment]
Have you tried
`#include <QtDesigner>`

since you are not using that library on your second file, your compiler might be dropping it.
