### ISSUE TITLE
libshiboken-python2.7.so.1.2 => not found

### ISSUE THREAD

**Issue by dashesy** [pyside/pyside-setup#50]
Installing from `pip` using `pip install pyside` in Fedora:

``` python
    from PySide import QtGui
```

Results in this:

``` text
    ImportError: libpyside-python2.7.so.1.2: cannot open shared object file: No such file or directory
```

``` bash
    ldd /usr/lib/python2.7/site-packages/PySide/libpyside-python2.7.so.1.2
```

Shows that `libshiboken-python2.7.so.1.2 => not found` but it resides in the same location as `libpyside-python2.7.so.1.2`, so I guess `libpyside-python2.7.so.1.2` needs some @rpath trickery to load it from the same location (`/usr/lib/python2.7/site-packages/PySide/libshiboken-python2.7.so.1.2`).

**Comment by dashesy** [comment]
I realized I have to call `pyside_postinstall.py -install` but that results in this error:

```text
/bin/pyside_postinstall.py: line 6: $'\r': command not found
/bin/pyside_postinstall.py: line 8: from: command not found
/bin/pyside_postinstall.py: line 9: from: command not found
/bin/pyside_postinstall.py: line 11: $'\r': command not found
/bin/pyside_postinstall.py: line 12: $'\r': command not found
/bin/pyside_postinstall.py: line 13: $'try:\r': command not found
/bin/pyside_postinstall.py: line 19: $'file_created\r': command not found
/bin/pyside_postinstall.py: line 20: is_bdist_wininst: command not found
/bin/pyside_postinstall.py: line 21: except: command not found
/bin/pyside_postinstall.py: line 22: is_bdist_wininst: command not found
/bin/pyside_postinstall.py: line 23: syntax error near unexpected token `('
'bin/pyside_postinstall.py: line 23: `    def file_created(file)
```

The fix is to add the shebang:
```
#!/usr/bin/env python
```

Then make sure CRLF is fixed with this:
```
sudo dos2unix /bin/pyside_postinstall.py
```

Then it fixes the `rpath`. I wonder why the `rpath` fix-up is not done during setupitself, it is much less likely to cause the problems and there wont be a need to call a `post_install` script. It is also very uncommon for a `setup.py` to touch anything in `/bin` and it may stop working in newer versions of `pip` altogether. On the other hand, during build the `.so` files can be patched with relative `rpath` values then packaged.

**Comment by ctismer** [comment]
Hi,

I realize that you are using a really outdated version of PySide,
because the current version on PyPi has no longer any reference to
pyside_postinstall at all.

> Installing from pip using pip install pyside in Fedora:

Can you please tell us from which century your Fedora version is?

I am not aware of what Fedora used to do, but I doubt that a current
version is that much behind?

But as said - I know a lot of Debian, OS X and Linux, but don't know
the status of Fedora. For sure this is a matter for their maintainers.

cheers - Chris


On 02/09/15 21:53, Ehsan Azar wrote:
> I realized I have to call |pyside_postinstall.py -install| but that
> results in this error:
> 
> |/bin/pyside_postinstall.py: line 6: $'\r': command not found
> /bin/pyside_postinstall.py: line 8: from: command not found
> /bin/pyside_postinstall.py: line 9: from: command not found
> /bin/pyside_postinstall.py: line 11: $'\r': command not found
> /bin/pyside_postinstall.py: line 12: $'\r': command not found
> /bin/pyside_postinstall.py: line 13: $'try:\r': command not found
> /bin/pyside_postinstall.py: line 19: $'file_created\r': command not found
> /bin/pyside_postinstall.py: line 20: is_bdist_wininst: command not found
> /bin/pyside_postinstall.py: line 21: except: command not found
> /bin/pyside_postinstall.py: line 22: is_bdist_wininst: command not found
> /bin/pyside_postinstall.py: line 23: syntax error near unexpected token `('
> 'bin/pyside_postinstall.py: line 23: `    def file_created(file)
> |
> 
> The fix is to add the shebang:
> 
> |#!/usr/bin/env python
> |
> 
> Then make sure CRLF is fixed with this:
> 
> |sudo dos2unix /bin/pyside_postinstall.py
> |
> 
> Then it fixes the |rpath|. I wonder why the |rpath| fix-up is not done
> during setupitself, it is much less likely to cause the problems and
> there wont be a need to call a |post_install| script. It is also very
> uncommon for a |setup.py| to touch anything in |/bin| and it may stop
> working in newer versions of |pip| altogether. On the other hand, during
> build the |.so| files can be patched with relative |rpath| values then
> packaged.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PySide/pyside-setup/issues/50#issuecomment-137225836>.
> 


-- 
Christian Tismer             :^)   tismer@stackless.com
Software Consulting          :     http://www.stackless.com/
Karl-Liebknecht-Str. 121     :     https://github.com/PySide
14482 Potsdam                :     GPG key -> 0xFB7BEE0E
phone +49 173 24 18 776  fax +49 (30) 700143-0023

**Comment by dashesy** [comment]
This is Fedora 21 but is updated from older versions so maybe the script is reminiscent of some ancient Fedora :)

I would not have needed the script if the `rpath` fix-up was done, so it is good that I had it I guess or I could not use PySide I get from pip. `pip` should not be related to Fedora.
