### ISSUE TITLE
error importing QtGui

### ISSUE THREAD

**Issue by akhilaananthram** [pyside/pyside-setup#51]
I am on OS X Yosemite 10.10.5, Python == 2.7.10, qt == 4.8.7, PySide == 1.2.2.
To install PySide, I used the commands:

```
brew install qt
pip install -U PySide
```

I am able to successfully execute `import PySide`.  However, when I execute `from PySide import QtGui` I get the error:

```
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/PySide/QtGui.so, 2): Library not loaded: libpyside-python2.7.1.2.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/PySide/QtGui.so
  Reason: image not found
```

I saw this [issue](https://github.com/PySide/PySide/issues/122) and seem to be having a similar problem.

If I execute the following it works:

```
cwd = os.getcwd()
import PySide
os.chdir(os.path.dirname(os.path.abspath(PySide.__file__)))
from PySide import QtGui
os.chdir(cwd)
```

I looked for a pyside_postinstall.py script but couldn't find one.  Is there a different work around for this?

**Comment by smallzhan** [comment]
Same problem here.  
last time I solved it with pyside_postinstall.py.

**Comment by luclu** [comment]
same, same.

**Comment by nicelifeBS** [comment]
I have the same issue with OSX 10.11.6 and pyside_postinstall.py is nowhere to be found. Any solution for this?
