### ISSUE TITLE
Error installing PySide on Python 3.5 via pip - subprocess.mswindows

### ISSUE THREAD

**Issue by ewerybody** [PySide/pyside-setup#53]
In Python 3.5 there is no more `subprocess.mswindows` it's now `subprocess._mswindows`!!
So installing via pip breaks with an error message:

    C:\Python35\Scripts>pip install pyside
    Collecting pyside
      Using cached PySide-1.2.2.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\Users\eric\AppData\Local\Temp\pip-build-zdgoarx_\pyside\setup.py", line 89, in <module>
            from utils import rmtree
          File "C:\Users\eric\AppData\Local\Temp\pip-build-zdgoarx_\pyside\utils.py", line 10, in <module>
            import popenasync
          File "C:\Users\eric\AppData\Local\Temp\pip-build-zdgoarx_\pyside\popenasync.py", line 26, in <module>
            if subprocess.mswindows:
        AttributeError: module 'subprocess' has no attribute 'mswindows'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\eric\AppData\Local\Temp\pip-build-zdgoarx_\pyside

I'd really like to know how to fix this. But atm I dunno :(

**Comment by lck** [comment]
Thanx for report. The fix should be trivial. I just don't have time to make new release and put it on PyPI.

**Comment by ctismer** [comment]
I hope it is trivial:

Python 3.5 does no longer use VC2010, but has rigorously moved to VS2015. That struck me as
well when I tried windows builds of PySide2. So you probably need to also use a different
Qt library build, etc. But maybe I'm just too careful...

**Comment by lck** [comment]
@ctismer you are right, the fix will be trivial but the build will not :/ well sooner or later i have to move to VS2015

**Comment by ctismer** [comment]
@lck Apropos: You can totally avoid the hassle of building Qt, yourself.
There is a compiler flag that was set in 2011 for whatever reason, and that makes
PySide on Windows incompatible with the downloadable Qt builds.

I was not sure why that was done. It is the difference between built-in Characters vs. having an explicit 4-Byte wchar_t type (something along these lines).
PyQt4 does not use this flag, so why do we?

I sat a while and wrote a script that analyses the config of Qt just to find out how to set this flag. But in the end, I think simply changing the default would be a good alternative?

What do you think?

**Comment by lck** [comment]
Hi Christian, I must rely on your judgment, because I don't have time to investigate the problem. Normally I would compile the Qt 4 against VC++ compiler compatible with Python 3.5. Can you point me in right direction what flag is needed to setup ? Any other steps ? Thanks.

**Comment by ctismer** [comment]
In the top-level CMakeLists.txt, I had to change this:
```
 if(MSVC)
-    set(CMAKE_CXX_FLAGS "/Zc:wchar_t- /GR /EHsc /DNOCOLOR /DWIN32 /D_WINDOWS /D_SCL_SECURE_NO_WARNINGS") # XXX
+    set(CMAKE_CXX_FLAGS "/Zc:wchar_t /GR /EHsc /DNOCOLOR /DWIN32 /D_WINDOWS /D_SCL_SECURE_NO_WARNINGS")
+    # XXX maybe check this setting dynamically!
 else()
```

That made my VS2010 build link with the downloaded Qt5 windows version.
But I see that I never checked if this applied to Qt4 as well. Wait.....

Ah, sorry, my fault! This has been `/Zc:wchar_t-` on Qt4.8 and was just changed to `/Zc:wchar_t` on Qt5.
Please forget what I said, and thanks for making me check this ;-)

**Comment by skilbjo** [comment]
I am encountering this issue on OS X, Python 3.5.0, VirtualEnv 1.11.5, and PySide 1.2.2:

````
Downloading/unpacking pyside
  Downloading PySide-1.2.2.tar.gz (9.3MB): 9.3MB downloaded
  Running setup.py (path:/Users/skilbjo/.virtualenvs/data/build/pyside/setup.py) egg_info for package pyside
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/skilbjo/.virtualenvs/data/build/pyside/setup.py", line 89, in <module>
        from utils import rmtree
      File "/Users/skilbjo/.virtualenvs/data/build/pyside/utils.py", line 10, in <module>
        import popenasync
      File "/Users/skilbjo/.virtualenvs/data/build/pyside/popenasync.py", line 26, in <module>
        if subprocess.mswindows:
    AttributeError: module 'subprocess' has no attribute 'mswindows'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/skilbjo/.virtualenvs/data/build/pyside/setup.py", line 89, in <module>

    from utils import rmtree

  File "/Users/skilbjo/.virtualenvs/data/build/pyside/utils.py", line 10, in <module>

    import popenasync

  File "/Users/skilbjo/.virtualenvs/data/build/pyside/popenasync.py", line 26, in <module>

    if subprocess.mswindows:

AttributeError: module 'subprocess' has no attribute 'mswindows'
````

**Comment by ctismer** [comment]
The patch for this is already in there, the version is just not tagged.
So pip will checkout 1.2.2 and not see the fixes which come later.
If you checkout the tip version and run setup.py with the option `--ignore-git`
then it should work.

**Comment by skilbjo** [comment]
@ctismer damnit, I am embarrassed I have to ask because I am new to `python` development, but is the workaround `pip install -e git+git@github.com:PySide/pyside2@e01ce681115a24f6bee0281d0c85f71b098bd8a1` ?

**Comment by ctismer** [comment]
Sorry, no, pyside2 is for Qt5 and not yet functional.

**Comment by cjauvin** [comment]
> If you checkout the tip version and run setup.py with the option --ignore-git then it should work.

I have tried to do this by doing:
```
$ git clone git@github.com:PySide/pyside-setup.git
$ cd pyside-setup
$ python setup.py install --ignore-git
```
which results in this error:
```
CMake Error: The source directory "/Users/christian/gh/pyside-setup/sources/shiboken" does not appear to contain CMakeLists.txt.
```
Any idea?

**Comment by ctismer** [comment]
Yes. Please do a recursive checkout, because this is a tree of repositories.
Something like this inside pyside-setup:
```$ git submodule update --init --recursive```
But note that this is a git question, not a pyside specific one that belongs here...

**Comment by cjauvin** [comment]
Thanks. It seems I can go a little further, but then hits another error:
```
CMake Error at /usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:
```
I agree my question is not pyside-specific, but I've been posting in this thread in the hope of finding a workaround for the same Python 3.5 and `subprocess` related problem which is at the origin of this thread, since version 1.2.3 (which fixes the problem if I understood correctly) is not yet available on PyPI. This bug completely breaks my ipython + matplotlib setup for Python 3.5, and I've just been looking for a solution, whatever it is.

**Comment by qguv** [comment]
Is anyone working on making PySide compatible with the current version of Python? (3.5.1 at time of writing)

**Comment by Mumbleskates** [comment]
Yeah, that sure would be nice.

**Comment by kjcole** [comment]
I have a `requirements.txt` with:

`PySide == 1.2.2`

and `pip3 install -r requirements.txt` still yields:

`    AttributeError: module 'subprocess' has no attribute 'mswindows'`

So, I would say the issue is not closed... Or is it a separate issue that just looks like this one?
