### ISSUE TITLE
Refuse build attempts on unsupported Python version

### ISSUE THREAD

**Issue by ctismer** [PySide/pyside-setup#57]
pyside-setup should check the version of Python it was tested on, and refuse other versions.

Happened right now: a bug report claiming PySide 1.2.2 not compiling on Python 3.5.0 .
This version is not listed as a supported version on PyPI, but it also does not
complain on an untested Python version. The first is not a bug, but the latter is, IMHO.

I think we should add that easy check.

**Comment by lck** [comment]
You are right, we can not support Vc++ compiler which is not supported by
qt 4. I will add the check before doing the final tag.
Dňa 6.10.2015 21:31 používateľ "Christian Tismer" <notifications@github.com>
napísal:

**Comment by ctismer** [comment]
Whow, I was not aware of this consequence. Makes sense!

Sent from my Ei4Steve

**Comment by lck** [comment]
Ok I was wrog, Qt4 supports VC++ up to version 2015, so we should too. Rebuilding Qt with VC++ 2015 for 32 and 65bit and making all wheels will take time...

**Comment by ctismer** [comment]
Closing, because we added an introspection function that checks the qualifier strings
