### ISSUE TITLE
updating to 1.2.4 breaks my app, rolled back to 1.2.2

### ISSUE THREAD

**Issue by ewerybody** [PySide/pyside-setup#59]
Hey! I'm on windows.
just looked over my packages and saw that there is a new PySide version 1.2.4, updated to it and nothing worked anymore! It didn't even say what's wrong! It was just like python stopped working. Even debuging from eclipse was just like it started the instance and after a moment it said it terminated :(

Is there a way I could give you any more info?
I did `pip uninstall PySide` and installed from the packages (https://download.qt.io/official_releases/pyside)  where there is actually not a 1.2.4 yet!

cheers:
ëRiC

**Comment by lck** [comment]
I have no problems running 1.2.4 on all supported Python versions. What is your Python version ? How did you install the 1.2.4 update ? You shuld use 'pip install -U pyside'. If you need you can download windows binaries from PySide PyPI page. Can you write exact steps how you installed pyside a how did you test that pyside is correctly installed ?

**Comment by ewerybody** [comment]
Hey Ok. I tried it on 3.4. 64. and yep I did exactly `pip install -U PySide`!
As I usually try first until shit breaks... So for the actual install as well. Dunno which version I hopped in tho :/

**Comment by lck** [comment]
Confirmed - Pyside 1.2.4 not working on Python 3.3 and 3.4, on both 32 and 64 bits.
Let you know when it's fixed.
Thanks

**Comment by lck** [comment]
Windows eggs (32 and 64 bit) are now uploaded to https://download.qt-project.org/official_releases/pyside/.
Please note, that to install the 64 bit packages for Python 3.3 and 3.4 you have to use the --allow-all-external pip parameter, for example:
c:\python34_64\Scripts\pip install -U pyside --allow-all-external
