### ISSUE TITLE
PySide windows binaries for Python 3.5

### ISSUE THREAD

**Issue by xantares** [pyside/pyside-setup#63]
Hi,

On windows, latest PySide stable is only available for Python versions as high as 3.4:
https://pypi.python.org/pypi/PySide/1.2.2#downloads
and (1.2.4) has less versions available
Would it be possible to get binaries for Python 3.5 ?

My goal is to make a newer version of PySide through conda package manager:
https://github.com/conda/conda-recipes/blob/master/python/pyside/meta.yaml
Conda is a multi-platform Python distro that ships Python packages by default for versions 2.7 and 3.5 in 32/34 bits.

xan.

**Comment by dickreuter** [comment]
It seems the only changed needed to support 3.5 is to adjust the setup.py file to include the new version and then recompile it.

**Comment by xantares** [comment]
would someone from pyside be kind enough to build a version and upload it to pypi, or should we wait for the next release (if it's planned) ?

**Comment by shakaran** [comment]
Probably they support Python 3.5 in PySide 2, check this:

https://wiki.qt.io/PySide2

**Comment by fredrikaverpil** [comment]
Not sure if it helps but I made a simple fork of PySide which has the Python version check removed: https://github.com/fredrikaverpil/pyside-setup

**Comment by fredrikaverpil** [comment]
Yes, Python 3.5 is supported with PySide2.
