### ISSUE TITLE
Can not find cmake even if I installed it successfully

### ISSUE THREAD

**Issue by rylanchiu** [pyside/pyside-setup#64]
My python version is `2.7.10` and I install `pyside` through: `pip -U install pyside`. But got such as error: `error: Failed to find cmake. Please specify the path to cmake with --cmake parameter.` However, I just download and installed cmake successfully. Could you please tell me how to solve this problem? Thanks a lot.

**Comment by cspears2002** [comment]
Are working on a Mac?  I first added CMake to my path and then ran pip.

$ PATH="/Applications/CMake.app/Contents/bin":"$PATH"
