### ISSUE TITLE
64-bit Windows wheels missing from PyPI

### ISSUE THREAD

**Issue by samh** [pyside/pyside-setup#66]
On PyPI, PySide 1.2.4 Windows binary wheels are available for 32-bit and 64-bit Python 2.x, but for Python 3.3 and 3.4, only the 32-bit wheels are available: https://pypi.python.org/pypi/PySide/1.2.4

The wheels seem to be built, at https://download.qt.io/official_releases/pyside/, but pip cannot install them normally.

**Comment by shakaran** [comment]
BUMP. Any progress with this?
