### ISSUE TITLE
qtmobility-dev missing package on Ubuntu 16.04

### ISSUE THREAD

**Issue by shakaran** [pyside/pyside-setup#67]
Following the s "[Building PySide on a Linux System (Ubuntu 12.04 - 14.04)](http://pyside.readthedocs.io/en/latest/building/linux.html)" document. I found in Ubuntu 16.04 that the package qtmobility-dev is missing from repos.

I don't know if it is a soft/hard dependency, but it would be good indicate that for Ubuntu 16.04 that instructions should be modified to reflect that the package qtmobility-dev is not available.

**Comment by rezhajulio** [comment]
+1 also have the same problem

**Comment by olayasturias** [comment]
Same problem in Ubuntu 16.04 running over a Raspberry Pi 3
